### ISSUE TITLE
Making it an add on for outlook

### ISSUE THREAD

**Issue by sconway24** [tayjones24/Nigerian-Prince-Detector-#18]
This will be a difficult task and the add on will have to be able to be integrated into outlook.

**Comment by FadiRached** [comment]
Plan on following [this](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) guide (Yeoman generator)

**Comment by FadiRached** [comment]
Might use react instead of pure HTML CSS JS because I've always wanted to learn it :D

**Comment by FadiRached** [comment]
Progress? 
![prince](https://user-images.githubusercontent.com/74790979/163032718-54153a41-3a73-4d32-ab34-dc3a04147b31.PNG)

**Comment by FadiRached** [comment]
How to load the custom add-in 

1. Go to https://outlook.live.com/owa/
2. Sign in to a non-jcu email account (you might have to create an outlook email address but I'm not sure)
3. Follow Steps 1-6 at [https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows#new-outlook-on-the-web](Sideload Outlook add-ins for testing) (ps: the manifest file mentioned in step 6 is at _Nigerian-Prince-Detector-\prince\dist\manifest.xml_)
4. Press the settings icon
5. Press "view all settings"
6. Go to Mail -> Customize actions
7. Scroll down to "Message surface" 
8.  Checkmark the "prince" option (or whatever your add-in is called)
9. Exit the settings
10. Open any message 
11. Press on the three dots at the top right of the message 
12. Press "prince" -> "Show taskpane"

**Comment by FadiRached** [comment]
Progress
![prince](https://user-images.githubusercontent.com/74790979/163077663-a5d62ab6-193d-4824-89e5-e0ace697464a.PNG)

**Comment by FadiRached** [comment]
Pretty happy with this. It displays the body of the email. Closing the issue for now.
![Capture](https://user-images.githubusercontent.com/74790979/164525156-0fe30a39-4242-465a-8efc-b9578548e4a9.PNG)
